### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by isontheline** [MaatheusGois/lan-scanner#4]
Hello @MaatheusGois Matheus 👋

I would like to thank you about your project 👍
Could you add some information about your project licensing please?

Have a nice day ☀️

**Comment by MaatheusGois** [comment]
https://github.com/MaatheusGois/lan-scanner/blob/develop/LICENSE

**Comment by isontheline** [comment]
Thank you so much @MaatheusGois 🙏
